services:
  - type: web
    name: sym-strapi
    env: node
    plan: starter
    buildCommand: |
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    autoDeploy: true
    branch: main
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        fromDatabase:
          name: sym-strapi-db
          property: connectionString
      - key: DATABASE_SSL
        value: "true"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
    healthCheckPath: /_health

  - type: postgres
    name: sym-strapi-db
    plan: starter
