services:
  - type: web
    name: sym-strapi
    runtime: node
    plan: starter
    branch: main
    autoDeploy: true
    buildCommand: |
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ""   # Fill in via Render UI after you create the Postgres DB
      - key: DATABASE_SSL
        value: "true"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
    healthCheckPath: /admin
