services:
  - type: web
    name: sym-strapi
    env: node
    plan: starter
    buildCommand: |
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    autoDeploy: true
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ""   # leave empty for now; we'll fill it after creating the DB
      - key: DATABASE_SSL
        value: "true"
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
    healthCheckPath: /_health
